services:
  php:
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html

  db:
    image: mysql:5.7
    container_name: specdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: specdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 15
    ports:
      - "3306:3306"
    volumes:
      - ./db/1-init-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/2-insert-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./db/3-update-schema.sql:/docker-entrypoint-initdb.d/3-update-schema.sql
      - ./db/4-insert-data.sql:/docker-entrypoint-initdb.d/4-insert-data.sql
      - ./db/5-queries.sql:/docker-entrypoint-initdb.d/5-queries.sql
