CREATE TABLE KATHGORIA(
  name VARCHAR(8) PRIMARY KEY,
  description VARCHAR(5000) NOT NULL
);

CREATE TABLE SXOLEIO(
  code VARCHAR(5) PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  address VARCHAR(45) NOT NULL,
  category VARCHAR(8) NOT NULL,
  FOREIGN KEY (category) REFERENCES KATHGORIA(name)
);

CREATE TABLE EKPAIDEYTIKOS(
  id INT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(35) NOT NULL,
  work_years INT NOT NULL,
  school VARCHAR(5),
  FOREIGN KEY (school) REFERENCES SXOLEIO(code)
);
